http:
 listener:
  host: "0.0.0.0"
  port: "9081"
  path: "/TravelOnTipCall/{ServiceType}"

db:
  oracle:
   host: "0.0.0.0"
   port:  "1521"
   username: "system"
   password:  "orcl"
   instance:  ""
   service: "orcl"
     
  